### ISSUE TITLE
jboss-javaee-6.0 spec BOM leaks Xalan dependency that is not published to Maven central

### ISSUE THREAD

**Issue by lincolnthree** [jboss/jboss-javaee-specs#3]
The dependency:

`<groupId>xalan</groupId>
  <artifactId>xalan</artifactId>
  <version>2.7.1.jbossorg-2</version>`

is missing in maven central, thus, dependency resolution frequently has issues -> http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22xalan%22%20AND%20a%3A%22xalan%22

This artifact IS however defined in the jboss nexus repository: 
https://repository.jboss.org/nexus/content/repositories/public/xalan/xalan/

~Lincoln

**Comment by njuneau** [comment]
@ctomc @wolfc , thank you for the fixes.

The JBoss Web site still mentions 3.0.2.Final as the recommended version ( http://www.jboss.org//boms/eap/jboss-javaee-6_0-all/index.html ). Should it be pushed to 3.0.3.Final over there as well?

**Comment by ctomc** [comment]
yes, web site should be updated
