### ISSUE TITLE
upgrade cdi-api to 1.2

### ISSUE THREAD

**Issue by ctomc** [jboss/jboss-javaee-specs#5]
WildFly 8.2 ships with CDI 1.2 but all our boms still specify 1.1.

**Comment by jamezp** [comment]
This has already been fixed, https://github.com/jboss/jboss-javaee-specs/blob/master/pom.xml#L52 as part of https://github.com/jboss/jboss-javaee-specs/pull/4.

**Comment by ctomc** [comment]
great, so all we need is a release and than use it in all boms

**Comment by jamezp** [comment]
That should be done too :) https://github.com/jboss/jboss-javaee-specs/releases/tag/jboss-javaee-7.0-1.0.2.Final
